import { Providers } from "@src/context/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const libre_franklin = Libre_Franklin({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-libre_franklin",
});

export const metadata: Metadata = {
	title: "Interactive PDF Learning Engine",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="en">
			<body className={libre_franklin.className}>
				<Providers>{children}</Providers>
				<Toaster />
			</body>
		</html>
	);
}
